config/routes.rb
Rails.application.routes.draw do

  resources :items

  get 'map/index', :as => :map
  get 'search', :controller => :search, :action => :index, :as => :search

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :coupons do
    member do
      post 'consume'
    end
  end 
  resources :shops do
    collection do
      get 'couponmgr'
    end
  end
  resources :activities
  root 'activities#index'

end

app/models/coupon.rb
require 'net/http'

class Coupon < ActiveRecord::Base
  belongs_to :shop
  has_many :coupon_use_records

  has_attached_file :feature_image, :styles => { :middle => "640x240" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :feature_image, :content_type => /\Aimage\/.*\Z/

  def self.search(keyword)
    Coupon.where("title LIKE ?", "%#{keyword}%")
  end

  def consume(phone_number)
    count_of_usage = coupon_use_records.where(:phone_number => phone_number).count
    return false if use_limit and count_of_usage > use_limit
    send_sms(phone_number)
  end

  def send_sms(phone_number)
    uri = URI('https://leancloud.cn')
    req_header = {}
    req_header['X-AVOSCloud-Application-Id'] = 'fu6avi97rq0tcegkgkxkliy28vgn2p12xcgpzlgza6yu3gw1'
    req_header['X-AVOSCloud-Application-Key']= 'ufuy8gmp8879dq9u5la84parquh5p90u1vb7z4dsj6gn3ely'
    req_header['Content-Type']               = 'application/json'

    Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
      res = http.post('/1.1/requestSmsCode', "{\"mobilePhoneNumber\":\"#{phone_number}\"}", req_header)
      
      coupon_use_record = CouponUseRecord.new
      coupon_use_record.phone_number = phone_number
      coupon_use_records << coupon_use_record
      true
    end
  end

  def self.confirm_code(phone_number, code)
    uri = URI('https://leancloud.cn')
    req_header = {}
    req_header['X-AVOSCloud-Application-Id'] = 'fu6avi97rq0tcegkgkxkliy28vgn2p12xcgpzlgza6yu3gw1'
    req_header['X-AVOSCloud-Application-Key']= 'ufuy8gmp8879dq9u5la84parquh5p90u1vb7z4dsj6gn3ely'
    req_header['Content-Type']               = 'application/json'

    Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https') do |http|
      res = http.post('/1.1/verifySmsCode/#{code}', "{\"mobilePhoneNumber\":\"#{phone_number}\"}", req_header)
      print res
      true
    end
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy, :consume]

  respond_to :html

  def index
    @coupons = Coupon.all
    respond_with(@coupons)
  end

  def show
    respond_with(@coupon)
  end

  def new
    @coupon = Coupon.new
    respond_with(@coupon)
  end

  def edit
  end

  def create
    @coupon = Coupon.new(coupon_params)
    @coupon.save
    respond_with(@coupon)
  end

  def update
    @coupon.update(coupon_params)
    respond_with(@coupon)
  end

  def destroy
    @coupon.destroy
    respond_with(@coupon)
  end

  def consume
    if params.include?(:phone_number)
      @status = @coupon.consume(params[:phone_number])
    end
  end

  private
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    def coupon_params
      params.require(:coupon).permit(:title, :subtitle, :shop_id, :detail)
    end
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/_form.html.erb
<%= form_for(@coupon) do |f| %>
  <% if @coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% @coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :shop_id %><br>
    <%= f.text_field :shop_id %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coupons/_listitem.html.erb
<li class="table-view-cell media common-card mb10">
  <a class="navigate-right disp-block no-padding no-margin" href="<%= coupon_path(coupon) %>" data-transition="slide-in">
    <div class="feature-img-wrap">
      <%= image_tag coupon.feature_image.url(:middle), :class => 'feature-img' %>
    </div>
    <div class="content-wrap plr20 ptb10">
      <p class="common-heading"><%= coupon.title %></p>
      <p><%= coupon.subtitle %></p>
    </div>
  </a>
</li> 

app/views/coupons/consume.html.erb
<% if @status %>
  ok，告诉营业员你收到的确认号码
<% else %>
  no，你使用次数过多了
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing coupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<%= render :partial => 'common/header' %>

<div class="content coupons coupons-index common-cardlist">
  <ul class="table-view  no-border">
    <% @coupons.each do |coupon| %>
      <%= render :partial => 'coupons/listitem', :locals => { coupon: coupon } %>
    <% end %>
  </ul>
</div>


<%= render :partial => 'common/nav', :locals => { section: 'coupons' } %>

app/views/coupons/new.html.erb
<h1>New coupon</h1>

<%= render 'form' %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<%= render :partial => 'common/header', :locals => { :back_left => true, :section => 'coupons' } %>


<div class="content common-show plr10">
  <header class="mt10 mb10">
    <h1 class="common-heading">
      <%= @coupon.title %>
    </h1>
    <div>
      <span>
        <%= fa_icon 'building' %>
        <%= link_to @coupon.shop.name, shop_path(@coupon.shop) %>
      </span>
    </div>
  </header>

  <div class="feature-img-wrap">
    <%= image_tag @coupon.feature_image.url(:middle), :class => 'feature-img' %>
  </div>

  <p>
    <%= @coupon.detail %>
  </p>

  <p>
    <form action="<%= consume_coupon_path(@coupon) %>" method="POST">
      <div>
        <input type="text" name="phone_number" placeholder="输入手机号使用">
      </div>
      <div>
        <input type="submit" value="提交" class="btn btn-primary">
      </div>
    </form>
  </p>
</div>