config/routes.rb
Rails.application.routes.draw do

  resources :items

  get 'map/index', :as => :map
  get 'search', :controller => :search, :action => :index, :as => :search

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :coupons do
    member do
      post 'consume'
    end
  end 
  resources :shops do
    collection do
      get 'couponmgr'
    end
  end
  resources :activities
  root 'activities#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_attached_file :feature_img, :styles => { :middle => "640x240" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :feature_img, :content_type => /\Aimage\/.*\Z/

  belongs_to :shop

  def self.search(keyword)
    Item.where("title LIKE ?", "%#{keyword}%")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @items = Item.all
    respond_with(@items)
  end

  def show
    respond_with(@item)
  end

  def new
    @item = Item.new
    respond_with(@item)
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    @item.save
    respond_with(@item)
  end

  def update
    @item.update(item_params)
    respond_with(@item)
  end

  def destroy
    @item.destroy
    respond_with(@item)
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:references, :title, :price, :summary, :detail)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :references %><br>
    <%= f.text_field :references %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_field :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_listitem.html.erb
<li class="table-view-cell media common-card mb10">
  <a class="navigate-right disp-block no-padding no-margin" href="<%= item_path(item) %>" data-transition="slide-in">
    <div class="feature-img-wrap">
      <%= image_tag item.feature_img.url(:middle), :class => 'feature-img' %>
    </div>
    <div class="content-wrap plr20 ptb10">
      <p class="common-heading"><%= item.title %></p>
      <p><%= item.summary %></p>
    </div>
  </a>
</li>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>References</th>
      <th>Title</th>
      <th>Price</th>
      <th>Summary</th>
      <th>Detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.references %></td>
        <td><%= item.title %></td>
        <td><%= item.price %></td>
        <td><%= item.summary %></td>
        <td><%= item.detail %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<%= render :partial => 'common/header', :locals => { :back_left => true, :section => 'activities' } %>

<div class="content common-show pt10 plr10">
  <header class="mt10 mb10">
    <h1 class="common-heading">
      <%= @item.title %>
    </h1> 
    <div>
      <span>
        <%= fa_icon 'building' %>
        <%= link_to @item.shop.name, shop_path(@item.shop) %>
      </span>
    </div>
  </header>

  <div class="feature-img-wrap">
    <%= image_tag @item.feature_img.url(:middle), :class => 'feature-img' %>
  </div>

  <p>
    <%= @item.detail %>
  </p>
</div>