config/routes.rb
Rails.application.routes.draw do

  resources :items

  get 'map/index', :as => :map
  get 'search', :controller => :search, :action => :index, :as => :search

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :coupons do
    member do
      post 'consume'
    end
  end 
  resources :shops do
    collection do
      get 'couponmgr'
    end
  end
  resources :activities
  root 'activities#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :shop

  has_attached_file :feature_image, :styles => { :middle => "640x240" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :feature_image, :content_type => /\Aimage\/.*\Z/

  def self.search(keyword)
    where("title LIKE ?", "%#{keyword}%")
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :summary, :detail)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/_listitem.html.erb
<li class="table-view-cell media common-card mb10">
  <a class="navigate-right disp-block no-padding no-margin" href="<%= activity_path(activity) %>" data-transition="slide-in">
    <div class="feature-img-wrap">
      <%= image_tag activity.feature_image.url(:middle), :class => 'feature-img' %>
    </div>
    <div class="content-wrap plr20 ptb10">
      <p class="common-heading"><%= activity.title %></p>
      <p><%= activity.summary %></p>
    </div>
  </a>
</li>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<%= render :partial => 'common/header' %>

<div class="content activities activities-index common-cardlist">
  <ul class="table-view no-border">
    <% @activities.each do |activity| %>
      <%= render :partial => 'activities/listitem', :locals => { activity: activity } %>
    <% end %>
  </ul>
</div>


<%= render :partial => 'common/nav', :locals => { section: 'activities' } %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<%= render :partial => 'common/header', :locals => { :back_left => true, :section => 'activities' } %>

<div class="content common-show pt10 plr10">
  <header class="mt10 mb10">
    <h1 class="common-heading">
      <%= @activity.title %>
    </h1> 
    <div>
      <span>
        <%= fa_icon 'building' %>
        <%= link_to @activity.shop.name, shop_path(@activity.shop) %>
      </span>
    </div>
  </header>

  <div class="feature-img-wrap">
    <%= image_tag @activity.feature_image.url(:middle), :class => 'feature-img' %>
  </div>

  <p>
    <%= @activity.detail %>
  </p>
</div>