config/routes.rb
Rails.application.routes.draw do

  resources :items

  get 'map/index', :as => :map
  get 'search', :controller => :search, :action => :index, :as => :search

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :coupons do
    member do
      post 'consume'
    end
  end 
  resources :shops do
    collection do
      get 'couponmgr'
    end
  end
  resources :activities
  root 'activities#index'

end

app/views/common/_header.html.erb
<% back_left = false if local_assigns[:back_left].nil? %>

<header class="bar bar-nav">
  <% if back_left %>
  <a class="icon icon-left-nav pull-left" href="
    <% case section %>
    <% when 'activities' %>
      <%= activities_path %>
    <% when 'shops' %>
      <%= shops_path %>
    <% when 'coupons' %>
      <%= coupons_path %>
    <% end %>
    " data-transition="slide-out"></a>
  <% end %>
  <h1 class="title">乐在嘉实</h1>
</header>

app/views/common/_nav.html.erb
<nav class="bar bar-tab">
  <a class="tab-item <% if section == 'shops' %> active <% end %>" href="<%= shops_path %>">
    <%= fa_icon 'building', :class => 'icon' %>
    <span class="tab-label">店铺</span>
  </a>
  <a class="tab-item <% if section == 'coupons' %> active <% end %>" href="<%= coupons_path %>">
    <%= fa_icon 'list-alt', :class => 'icon' %>
    <span class="tab-label">优惠</span>
  </a>
  <a class="tab-item <% if section == 'activities' %> active <% end %>" href="<%= activities_path %>">
    <%= fa_icon 'child', :class => 'icon' %>
    <span class="tab-label">活动</span>
  </a>
  <a class="tab-item <% if section == 'search' %> active <% end %>" href="<%= search_path %>">
    <span class="icon icon-search"></span>
    <span class="tab-label">探索</span>
  </a>
  <a class="tab-item <% if section == 'map' %> active <% end %>" href="<%= map_path %>">
    <%= fa_icon 'globe', :class => 'icon' %>
    <span class="tab-label">地图</span>
  </a>
</nav>